# 在whole_process模式下进行实验
# dqn-dynamic
# 训练
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage train --save_model True --replace_window 25 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# 测试
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 25 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 50 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 100 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 150 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 200 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 300 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 400 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 500 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 600 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4

# sr-replace
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-25 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-50 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-100 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-150 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-200 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-300 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-400 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-500 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output whole_process_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-600 --workload=whole_process --model-type=mixed --num-devices 16 --num_devices_per_node 4


# 在offline模式下进行实验
# dqn-dynamic
# 训练
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage train --save_model True --replace_window 5 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# 测试
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 10 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 20 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 40 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 70 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 100 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy dqn-dynamic --rl_stage test --replace_window 130 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4

# sr-replace
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-10 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-20 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-40 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-70 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-100 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
# python hpsc25_artifact/window_size_affect/my_general_model_case.py --exp-ids goodput_vs_num_devices --output azure_v1_window_size_affect.tsv --exp-name window_size_affect --policy sr-replace-130 --workload=azure_v1 --model-type=mixed --num-devices 16 --num_devices_per_node 4
